id: P006869
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG12533
  title: རྟེན་འབྲེལ་རབ་བདུན་མའི་ཞལ་གདམས་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    2769323e89a9469f8d5e89284d2690be:
      image_group_id: I1KG12560
      title: ''
      volume_number: 1
      total_pages: 586
      base_file: v001.txt
