id: I5C48B65E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T05:59:13+00:00'
last_modified: '2022-06-08T07:27:35.119101+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12533
  title: རྟེན་འབྲེལ་རབ་བདུན་མའི་ཞལ་གདམས་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6222':
      image_group_id: I1KG12560
      title: ''
      total_pages: 586
      order: 1
      base_file: 6222.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
